[package]
edition = "2021"
name = "yew-weather"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stylist = {version = "0.10", features = ["yew_integration"]}
yew = "0.19"

[features]
yew_integration = []
